---
title: "Stm_diss_3"
output: html_document
---

```{r}
library(stringr)
library(tm)
library(stm)
library(lubridate)
library(dplyr)
library(quanteda)
library(stringdist)
library(tidystringdist)
library(ggplot2)
library(stargazer)
library(sjmisc)
library(ngram)
library(sjlabelled)

```

Making Covariates for The STM Model.


```{r}

# List of Covariates. The Data was already process so most 

conservative <- c( "The New York Post", "The Wall Street Journal", "Richmond Times Dispatch", "The Detroit News", "The Daily Oklahoman", "Human Events", "Human Events Online", "Fox News Network")

terrorism_list <- c("Holy Land Foundation", "Benevolence International Foundation", "Al Harmain Islamic Foundation", "Global Relief Foundation")

International_Relief <- "Albanian Islamic Cultural Center|Algerian Relief Foundation|Benevolence International|American Bosnia-Herzegovina Relief Fund|Az Zaitoon Pathan Foundation|Badr for Relief and Developement |Benevolence International|The Bosnia Relief Fund|Bosnian-American Cultural Association|Care International|Charitable Society for Social Welfare |Chechen-Ingush Society of America|Consultative Committee of Indian Muslims|Al-Ehsan Charitable Relief Organization |Health Resource Center for Palestine|Help the Needy |Fund for Afghan Relief and Development|Global Relief Foundation|Gulf Medical Relief|Holy Land Foundation|HOPE International|ICNA|Helping Hand|IKRE Fund|International Relief Association|Islamic African Relief Agency|Islamic-American Zakat Foundation|Islamic Call Organization|Islamic Relief USA|United Muslim Relief|Jerrahi Order|Kashmir Family Aid|Malsia Humanitarian Fund|Life for Relief and Development|Mercy International|Muslim Immigration and Refugee Services|Baitulmaal|Islamic Hope Foundation|Hope Islamic Center|Middle East Childrens Alliance|Islamic Medical Association of North America Inc|Save Bosnia Now|Sisters in Struggle|Somali Relief Fund|Sos|International Relief Organization|International Islamic Charitable Organization|Ummah Relief International|Palestine Childrens Relief Fund|Palestine Right To Return Coalition"



```


# Reading Data


```{r}

data_filtered_unique <- read.csv("H:/STM_Lexis_Nexis/data_ngos_ml_final_inshallah.csv")

data_filtered_unique$text <- as.character(data_filtered_unique$text)
# Making Various Covariates through dplyr

data_filtered_unique <- data_filtered_unique  %>% mutate(Year = year(Date_1)) %>%  mutate(post_911 = ifelse(as.Date(Date_1) > "2001-9-11",1,0 )) %>% mutate(conservative_news = ifelse(Newspaper %in% conservative, 1,0)) %>% mutate(terrorism=ifelse(grepl(paste(terrorism_list, collapse = '|'),keyword, ignore.case = TRUE), 1, 0)) %>% mutate(document = sapply(strsplit(as.character(docname), "[.]"), "[", 1)) %>% mutate(year_2001 = ifelse(as.Date(Date_1) >= "2001-09-11" & as.Date(Date_1) <= "2001-12-31",1,0 )) %>% mutate(relief= ifelse(grepl(International_Relief, text, ignore.case = TRUE), 1,0))




```

# Further Making Covariates

```{r}


# Counting words in each paragrapsh
data_filtered_unique$word_count <- sapply(data_filtered_unique$text, wordcount)

 # Making covariate 2001 by subtracting each year with 2001.
data_filtered_unique$year_2001 <- data_filtered_unique$Year - 2001
```


Processing the text for stm.
```{r}
processed <- textProcessor(data_filtered_unique$text, metadata =data_filtered_unique)

out <- prepDocuments(processed$documents, processed$vocab, processed$meta)
docs <- out$documents
vocab <- out$vocab
meta  <-out$meta


# Making a separate interaction variable since stm regression does not allow an interaction to be plotted in the plotting. Discussed Later.
out_1 <- out$meta
out_1$interaction <- out_1$post_911 * out_1$year_2001


```

Finding the best number of topic for the stm from 5 to 40 topics.

```{r}
storage <- searchK(out$documents, out$vocab, K = 5:40,  prevalence = ~ post_911 * year_2001 + relief  + conservative_news + terrorism + word_count,  data = out$meta, seed = 8458159)


#Plotting Results. 22 Topics seemd to be the best option. Also looked at topics to see if they made sense.

plot(storage)

plot(storage$results$K, storage$results$exclus, ylab = 'Exclusivity', xlab = 'Topics')
plot(storage$results$K, storage$results$semcoh, ylab = 'Semantic Coherence', xlab = 'Topics')



```

Running Stm models

```{r}

stm_model <- stm(out$documents, out$vocab, K = 22,  prevalence = ~ post_911 * year_2001 + relief  + conservative_news + terrorism + word_count,  data = out$meta, seed = 8458159)


prep <- estimateEffect(1:22 ~   post_911 * year_2001 + relief  + conservative_news + terrorism + word_count , stm_model,  meta = out$meta, uncertainty = "Global")

# Ran this regression since stm models does not allow an interaction to be plotted. Discussed later

prep_1 <- estimateEffect(1:22 ~   post_911 + year_2001 + interaction + relief  + conservative_news + terrorism + word_count , stm_model,  meta = out_1, uncertainty = "Global")



# Summary of the regressions
summary(prep)
summary(prep_1)


#Summary of the topics

plot(stm_model, type = "summary", xlim = c(0, 1))


```

Reading examples of each topic to better understand each of them on by one.

```{r}
findThoughts(stm_model, texts = data_filtered_unique$text,  n = 10, topics = 11)$docs[[1]]
Topic 1: Government Arrest (Increase 9/11)
Topic 2: Holy Land Foundation
Topic 3: Iraq war
Topic 4: Relief Efforts
Topic 5: Global Relief Foundation
Topic 6: Council on American-Islamic Relations (Less post 9/11)
Topic 7: Events
Topic 8: Benevolence International Foundation (More 9/11)
Topic 9: Prayer (Less 911)
Topic 10: Santa Clara Property Issue
Topic 11: Not clear
Topic 12: Rabih Haddad Arrest (Global Relief Foundation)
Topic 13: Islamic Center Activities (Less post 9/11)
Topic 14: Promoting Tolerance?
Topic 15: Islamic Education
Topic 16: Islamic Architecture
Topic 17: Donor Arrests (Increase 9/11)
Topic 18: Islamophobic Attacks
Topic 19: Islamic Circle of North America
Topic 20: Photos/Intros
Topic 21: Condemning Islamophobia (Increase post 9/11)
Topic 22: Funeral Prayer

  



```








```{r}

# Plotting the Results with the summary and labels of each topic

plot(stm_model, type="summary",  custom.labels = c(' Government Arrest', 'Holy Land Foundation', 'Iraq war', 'Relief Efforts', 'Global Relief Foundation','Council on American-Islamic Relations','Events', 'Terrorism', 'Prayer', 'Santa Clara Property Issue', 'Political Advocacy','Rabih Haddad Arrest', 'Islamic Center Activities', 'Promoting Tolerance', 'Islamic Education', 'Islamic Architecture', 'Donor Arrests', 'Islamophobic Attacks', 'Islamic Circle of North America', 'Photos',
'Condemning Islamophobia', 'Funeral Prayer' ))



# Plotting the effect of 9/11 on the topics of interest.


plot(prep, covariate = "post_911", topics = c(1,8, 17, 21, 9, 13),  model = stm_model, method = "difference",  cov.value1 = 1, cov.value2 = 0, xlim = c(-.1, .1), labeltype = "custom", custom.labels = c("Government Srutiny", "Terrorism",  "Donor Arrests",  "Condemning Islamophobia", "Prayer",  "Community Building"    ))


# Plotting the effect of 9/11 and year interaction. Given in appendix.

plot(prep_1, covariate = "interaction",   model = stm_model, method = "difference",  cov.value1 = 1, cov.value2 = 0, xlim = c(-.1, .1), cex.lab=1.5, labeltype = "custom", custom.labels = c(' Government Arrest', 'Holy Land Foundation', 'Iraq war', 'Relief Efforts', 'Global Relief Foundation','Council on American-Islamic Relations','Events', 'Terrorism', 'Prayer', 'Santa Clara Property Issue', 'Political Advocacy','Rabih Haddad Arrest', 'Islamic Center Activities', 'Promoting Tolerance', 'Islamic Education', 'Islamic Architecture', 'Donor Arrests', 'Islamophobic Attacks', 'Islamic Circle of North America', 'Photos',
'Condemning Islamophobia', 'Funeral Prayer' ))




```


Plotting various covariates for the appendices.

```{r}

plot(prep,   covariate = "post_911",   model = stm_model, method = "difference",  cov.value1 = 1, cov.value2 = 0, xlim = c(-.2, .1), cex.lab=1.5, labeltype = "custom", custom.labels = c('Government Arrest', 'Holy Land Foundation', 'Iraq war', 'Relief Efforts', 'Global Relief Foundation','Council on American-Islamic Relations','Events', 'Terrorism', 'Prayer', 'Santa Clara Property Issue', 'Political Advocacy','Rabih Haddad Arrest', 'Community Activities', 'Promoting Tolerance', 'Islamic Education', 'Islamic Architecture', 'Donor Arrests', 'Islamophobic Attacks', 'Islamic Circle of North America', 'Photos',
'Condemning Islamophobia', 'Funeral Prayer' ))


plot(prep_1, covariate = "interaction",   model = stm_model, method = "difference",  cov.value1 = 1, cov.value2 = 0, xlim = c(-.1, .1), cex.lab=1.5, labeltype = "custom", custom.labels = c('Government Arrest', 'Holy Land Foundation', 'Iraq war', 'Relief Efforts', 'Global Relief Foundation','Council on American-Islamic Relations','Events', 'Terrorism', 'Prayer', 'Santa Clara Property Issue', 'Political Advocacy','Rabih Haddad Arrest', 'Community Activities', 'Promoting Tolerance', 'Islamic Education', 'Islamic Architecture', 'Donor Arrests', 'Islamophobic Attacks', 'Islamic Circle of North America', 'Photos',
'Condemning Islamophobia', 'Funeral Prayer' ))





plot(prep, ,  covariate = "relief",   model = stm_model, method = "difference",  cov.value1 = 1, cov.value2 = 0, xlim = c(-.2, .3), cex.lab=1.5, labeltype = "custom", custom.labels = c('Government Arrest', 'Holy Land Foundation', 'Iraq war', 'Relief Efforts', 'Global Relief Foundation','Council on American-Islamic Relations','Events', 'Terrorism', 'Prayer', 'Santa Clara Property Issue', 'Political Advocacy','Rabih Haddad Arrest', 'Community Activities', 'Promoting Tolerance', 'Islamic Education', 'Islamic Architecture', 'Donor Arrests', 'Islamophobic Attacks', 'Islamic Circle of North America', 'Photos',
'Condemning Islamophobia', 'Funeral Prayer' ))

plot(prep, ,  covariate = "terrorism",   model = stm_model, method = "difference",  cov.value1 = 1, cov.value2 = 0, xlim = c(-.3, .45), cex.lab=1.5, labeltype = "custom", custom.labels = c('Government Arrest', 'Holy Land Foundation', 'Iraq war', 'Relief Efforts', 'Global Relief Foundation','Council on American-Islamic Relations','Events', 'Terrorism', 'Prayer', 'Santa Clara Property Issue', 'Political Advocacy','Rabih Haddad Arrest', 'Community Activities', 'Promoting Tolerance', 'Islamic Education', 'Islamic Architecture', 'Donor Arrests', 'Islamophobic Attacks', 'Islamic Circle of North America', 'Photos',
'Condemning Islamophobia', 'Funeral Prayer' ))


plot(prep, ,  covariate = "conservative_news",   model = stm_model, method = "difference",  cov.value1 = 1, cov.value2 = 0, xlim = c(-.3, .45), cex.lab=1.5, labeltype = "custom", custom.labels = c('Government Arrest', 'Holy Land Foundation', 'Iraq war', 'Relief Efforts', 'Global Relief Foundation','Council on American-Islamic Relations','Events', 'Terrorism', 'Prayer', 'Santa Clara Property Issue', 'Political Advocacy','Rabih Haddad Arrest', 'Community Activities', 'Promoting Tolerance', 'Islamic Education', 'Islamic Architecture', 'Donor Arrests', 'Islamophobic Attacks', 'Islamic Circle of North America', 'Photos',
'Condemning Islamophobia', 'Funeral Prayer' ))

```

Visualizing Various Topics

```{r}

par(mfrow=c(3,3))
for (i in 1:22)
{
  plot(stm_model, "year", method = "continuous", topics = i, main = paste0(model.stm.labels$prob[i,1:3], collapse = ", "), printlegend = F)
}

```

